services:
  ufiles:
    build: app
    restart: unless-stopped
    command: python app.py
    env_file:
      - .env
    volumes:
      - ./app:/app
    # ports:
    #   - 3016:3000
    networks:
      - mongo-net
      - traefik-net
      - ufiles-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}.rule=${DOMAINS}"
      # - "traefik.http.routers.${PROJECT_NAME}.middlewares=https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=${DOMAINS}"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-net"

networks:
  mongo-net:
    external: true
  traefik-net:
    external: true
  ufiles-net:
    name: ufiles-net
