"""init

Revision ID: b3282ae1c90e
Revises: 
Create Date: 2024-06-26 14:18:22.494906

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3282ae1c90e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("s3_bucket_name", sa.String(), nullable=True),
        sa.Column("s3_domain", sa.String(), nullable=True),
        sa.Column("s3_endpoint", sa.String(), nullable=True),
        sa.Column("s3_access_key", sa.String(), nullable=True),
        sa.Column("s3_secret_key", sa.String(), nullable=True),
        sa.Column("s3_region", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_business_id"), "business", ["id"], unique=False)
    op.create_table(
        "objects",
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("object_hash", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("s3_key"),
    )
    op.create_index(op.f("ix_objects_s3_key"), "objects", ["s3_key"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=True),
        sa.Column("parent", sa.UUID(), nullable=True),
        sa.Column("is_directory", sa.Boolean(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["business.id"],
        ),
        sa.ForeignKeyConstraint(
            ["s3_key"],
            ["objects.s3_key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_objects_s3_key"), table_name="objects")
    op.drop_table("objects")
    op.drop_index(op.f("ix_business_id"), table_name="business")
    op.drop_table("business")
    # ### end Alembic commands ###
